name: CI

on: [push]

env: 
  DOCKER_IMAGE_NAME: resume-latext

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build Docker image
      run: ./scripts/docker.sh      
    - name: Run Docker image
      run: |
        docker run \
          --mount type=bind,source=$(pwd)/,target=/app/current $DOCKER_IMAGE_NAME
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git status
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
