name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Run git update script
      run: ./scripts/pushToGit.sh
    - name: Run Docker process
      run: ./scripts/docker.sh
    - name: Run git update script
      run: ./scripts/pushToGit.sh
